### ISSUE TITLE
before-package on theos-jailed?

### ISSUE THREAD

**Issue by Antonn1** [kabiroberai/theos-jailed#10]
hey!

Im not sure if this is a problem on my end or with theos-jailed. but i cannot for the life of me figure out how to copy/edit something inside the .theos/_/Payload/xxx.app before the app gets repackaged by the script.

I have tried internal-package::, before-package, after-package, before-stage, after-stage, etc and they all either run before the folder above is created or after the .ipa has been packaged by the script.

how am i supposed to tell my makefile to do something right before theos starts repackaging the .app?

**Comment by kabiroberai** [comment]
Hey,

If you create a Resources directory in your project folder, Theos Jailed will merge any files inside it with the app's root directory. To automate this you can copy the files required in before-package.

**Comment by Antonn1** [comment]
thank you! the Resources directory worked, but the before-package:: does not work for me, it always tries to copy said files before the app is extracted.

Resources will do fine for me. :)

thank you again!!

**Comment by kabiroberai** [comment]
No problem! You can also try copying the files you want into Resources in before-package, something like

    before-package::
        @cp /path/to/file Resources

**Comment by Antonn1** [comment]
ahhh! that yes! I was looking to copy it into the _ directory directly. but creating the Resources folder works fine too!

thank you for everything!
