### ISSUE TITLE
make package error - undefinied symbols for architecture armv7

### ISSUE THREAD

**Issue by strano666** [kabiroberai/theos-jailed#11]
Hi to all.

I've followed the wiki "Usage" to try this project mixed with the tutorial of BishopFox, because of iOS 10. So the tweak that i've used is linked in [this page](https://www.bishopfox.com/blog/2015/05/rethinking-repackaging-ios-apps-part-2/
)

When i try to run `make package` command i've this error
```
> Making all for tweak Trulia…
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (armv7)…
==> Compiling /Users/***/Develop/theos/mod/jailed/lib/fishhook/fishhook.c (armv7)…
==> Linking tweak Trulia (armv7)…
Undefined symbols for architecture armv7:
  "_CYListenServer", referenced from:
      _logosLocalCtor_8bb45991(int, char**, char**) in Tweak.xm.b156651c.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/Users/***/Develop/trulia/.theos/obj/debug/armv7/Trulia.dylib] Error 1
make[2]: *** [/Users/***/Develop/trulia/.theos/obj/debug/armv7/Trulia.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [Trulia.all.tweak.variables] Error 2
```

The set up is:
Mac Mini equipped with 

- mac OS 10.12.3, 
- kernel Darwin 16.4
- Xcode 8.2.1

**Comment by kabiroberai** [comment]
It seems that you're trying to integrate Cycript into Tweak.xm, which isn't required because every debug build already comes with Cycript installed. If you want, you can set Trulia_USE_CYCRIPT=0 and then see how it's done in addons/cycript in this repo.

**Comment by strano666** [comment]
It works. Thank you!

I've modified Tweak.xm of that page, removing the line 12-16. Now the problem is with istallation. Another issue :)
