### ISSUE TITLE
Install ipa error - AMDeviceSecureInstallApplication

### ISSUE THREAD

**Issue by strano666** [kabiroberai/theos-jailed#12]
Running `make package` command i've this error

```
> Making all for tweak Trulia…
make[2]: Nothing to be done for `internal-library-compile'.
> Making stage for tweak Trulia…
==> Unpacking trulia-cracked.ipa…
==> Setting bundle ID…
==> Setting display name…
==> Copying dependencies…
==> Injecting dependencies…
==> Signing Trulia.app…
==> Repacking Trulia.app…
==> Waiting for iOS device to be connected…
==> Using J72AP 'iPad di Alfonso Solimeo' (01c5e677f2057b33ee76dd8aa0d2b9098a409043).…
==> Installing: 65%
==> Error: Error 0xe80000c8: unknown. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
```

i've run also `ios-deploy` with verbose flag on the *.app generated during the making, to see the output. It block on `PreflightingApplication`

```
$: sudo ios-deploy -v -i 01c5e677f2057b33ee76dd8aa0d2b9098a409043 -b Payload/Trulia.app
...............
[ 52%] CreatingStagingDirectory
[ 57%] ExtractingPackage
[ 60%] InspectingPackage
[ 60%] TakingInstallLock
[ 65%] PreflightingApplication
2017-02-16 10:13:19.871 ios-deploy[2985:71670] [ !! ] Error 0xe80000c8: unknown. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
```
I've done all the passages on the [Usage Wiki](https://github.com/kabiroberai/theos-jailed/wiki/Usage) only on the step 9 i've run the command without file.mobileprovisining because after the `make info` the instructions are different. Is the error here?

**Comment by kabiroberai** [comment]
Could you try installing the IPA through Xcode?

**Comment by strano666** [comment]
Yep.

Xcode returns me:

> App installation failed
> This application is not built for this device

**Comment by kabiroberai** [comment]
This means the device on which you extracted the ipa does not have the same architecture as the target device (64 vs 32 bit). A fix for this is to install the app onto your jailbroken device through iTunes on a computer, which will install all architectures instead of just that of the device.

**Comment by strano666** [comment]
The devices have same architecture :(
i've extracted the app from a iphone 6s and i'm trying to install into an iPad Air.
I've also checked the app extracted with otool

```
$ otool -Vh Payload/Trulia.app/Trulia 
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64   ARM64        ALL  0x00     EXECUTE    95       8576   NOUNDEFS DYLDLINK TWOLEVEL PIE
```

**Comment by kabiroberai** [comment]
Try an IPA from a website like http://virulent.pw/ipasearch/ to see whether that works

**Comment by strano666** [comment]
Very kind!
Now it works! 
How it is possible? bad decrypt?

**Comment by kabiroberai** [comment]
Welcome! I think it's because you decrypted the app on an iPhone, but installed it on an iPad. You can use the iTunes workaround highlighted above to fix this. Let me know if it works, and I'll close this issue.

**Comment by strano666** [comment]
Sorry for the late @kabiroberai but for now i don't have a jailbroken device :(

**Comment by gav1474** [comment]
can you help me to install this theos jailed please? getting opt error ...

**Comment by kabiroberai** [comment]
@gav1474 please create a new issue so that I can track it, but first see [Troubleshooting](https://github.com/kabiroberai/theos-jailed/wiki/Troubleshooting) for common errors and solutions.

**Comment by kabiroberai** [comment]
@strano666 ok, I'm closing this since I think the problem was that you didn't decrypt a universal version.
