### ISSUE TITLE
make package error

### ISSUE THREAD

**Issue by kuteteen** [kabiroberai/theos-jailed#13]
ld: warning: object file (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/lib/darwin/libclang_rt.ios.a(emutls.c.o)) was built for newer iOS version (6.0) than being linked (5.0)
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_SCLAlertView", referenced from:
      objc-class-ref in Tweak.xm.05cd20bb.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

??? plz fix

**Comment by kabiroberai** [comment]
Try adding `TARGET = ::6.0` at the top of `Makefile`

**Comment by kuteteen** [comment]
Similar problem continues :(( help me guide add SCLAlertView in tweak.xm

**Comment by kuteteen** [comment]
help me @kabiroberai

**Comment by Antonn1** [comment]
this is a problem with scl and not theos jailed

**Comment by kabiroberai** [comment]
Sorry for the delay, but if you still haven't solved it check out [this article](http://iphonedevwiki.net/index.php/Theos/Troubleshooting#Undefined_symbols) for help. Also, make sure you've linked the framework correctly by following [the guide](https://github.com/kabiroberai/theos-jailed/wiki/Usage#using-frameworks) on the wiki.

**Comment by kabiroberai** [comment]
Closing this for now, but I can reopen it once you respond.
