### ISSUE TITLE
MSHookFunction - it works?

### ISSUE THREAD

**Issue by strano666** [kabiroberai/theos-jailed#15]
Hi, i've successfully installed Theos Jailed and used it.

With a simply hook that logs a sentence, it's all ok.
Also if i try to hook a method inside an app which i made myself.

But i've some problem with MSHookFunction aka %hookf, useful to intercept system call.
I've no returns by these functions, neither with the app which i wrote where it's sure that the interested function is called.

It's possible that is an issue due to the jailed situation? Do you have done any test with these functions?

**Comment by kabiroberai** [comment]
MSHookFunction doesn't actually work in jailed environments, so I've included [fishhook](https://github.com/facebook/fishhook) as a replacement. Set `TWEAK_NAME_USE_FISHHOOK=1` to enable it, and then `#import <fishhook.h>` in Tweak.xm.

**Comment by strano666** [comment]
Tnx @kabiroberai !!
I've tried Fishhook and it's all ok!

**Comment by hbouhadji** [comment]
Hi,

But when it's a private function, how we can do please ?

exemple 
`unsigned long ExtractString = (_dyld_get_image_vmaddr_slide(0) + 0x14e2c1) | 0x00000001;`
Fishhook can't hook private function I think, only mshookfunction

Thanks you, I really need that
@kabiroberai
