### ISSUE TITLE
error 1

### ISSUE THREAD

**Issue by gav1474** [kabiroberai/theos-jailed#16]
hello folks !
I am getting this error ...

==> Error: Could not find profile '*'
make: *** [internal-package] Error 1

any suggestions ?
Thanks

**Comment by kabiroberai** [comment]
Hey,

Unless you're enrolled in the (paid) Apple Developer Program, you'll need to create a provisioning profile to sign IPAs. To do this just run `make info` and follow the instructions there.

**Comment by gav1474** [comment]
Yeah thanks i find out the issue, i had to use  "make package CODSIGN_IPA=0 "  and then resign the app with dev certificate or cydia impactor, 
you can now close the issue
