### ISSUE TITLE
Unable to invoke the FLEX toolbar

### ISSUE THREAD

**Issue by ninoz** [kabiroberai/theos-jailed#18]
My App has installed okay and I can access the cycript service however I cant seem to trigger the FLEX toolbar by using the F or ? keys.

Im installing directly to a device (iPhone7+ not a simulator)

Do I need to do something in particular to have the menu appear?

**Comment by kabiroberai** [comment]
To show the FLEX toolbar, you need to set `TweakName_USE_FLEX = 1` in Makfile (replace TweakName with the name of your tweak). Once you do that, it should automatically appear when you deploy the app to your device.

**Comment by ninoz** [comment]
Ah thats done the trick!

bizzarely "TWEAK_NAME_USE_CYCRIPT=1" works without actually having to replace the name 

Thanks for the swift reply!

**Comment by kabiroberai** [comment]
Welcome! Btw TWEAK_NAME_USE_CYCRIPT doesn't actually do anything, it's just that Cycript is enabled by default on debug builds. So Cycript should work even if you remove that line. 

To disable Cycript when you're distributing the IPA, set `FINALPACKAGE=1`.
