### ISSUE TITLE
dylilbs not injecting

### ISSUE THREAD

**Issue by nickyd365** [kabiroberai/theos-jailed#19]
I am following directions as shown but cannot get the dylib to inject. I have tried a few that I've used with libloader to make sure its not the tweak. It will make package install but not with the dylib. Thoughts?

**Comment by kabiroberai** [comment]
Could you send me your `Makefile` please?

**Comment by nickyd365** [comment]
TWEAK_NAME_INJECT_DYLIBS = Napstelife.dylib
MODULES = jailed
include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Napster
DISPLAY_NAME = Napster
BUNDLE_ID = com.jc.napster

Napster_FILES = Tweak.xm
Napster_IPA = /Users/jc/Desktop/Napster.ipa

include $(THEOS_MAKE_PATH)/tweak.mk

**Comment by kabiroberai** [comment]
You have to replace `TWEAK_NAME_INJECT_DYLIBS` with `Napster_INJECT_DYLIBS`

**Comment by nickyd365** [comment]
Changing TWEAK_NAME crashes the app upon install.

Keeping TWEAK_NAME on deezer worked just fine but most are crashing or not injecting. I tried Kenneth Poons method and they inject.

**Comment by nickyd365** [comment]
any thoughts???

**Comment by kabiroberai** [comment]
If you leave it as `TWEAK_NAME`, Theos Jailed ignores the line entirely. Run `otool -L Napsterlife.dylib` and let me know what it says

**Comment by nickyd365** [comment]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'Napstelife.dylib': No such file or directory

**Comment by kabiroberai** [comment]
Run that command in your tweak directory (or wherever the dylib is located)

**Comment by nickyd365** [comment]
figured it out. took a lot but I've got them injecting. Also can inject with homemade tweak.xm. I can inject bundles now too. Needs work on my end. Thanks bro!

**Comment by kabiroberai** [comment]
Welcome! If you have any other problems, feel free to create another issue.
