### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by mtshare** [kabiroberai/theos-jailed#2]
Hi, I'm trying to install it but I keep getting this even If I have the $THEOS environment variable set in "~/.bash_profile":
Error: "" is not a directory. Aborting...

So i declared the $THEOS PATH inside the install script and then I got this:
ln: module/bin/update: File exists

Any suggestions?

**Comment by kabiroberai** [comment]
I'm not too sure about the first part, but you can fix the `ln` issue by deleting `module/bin/update`. Just run `rm module/bin/update`, and then try `./install` again.

**Comment by kabiroberai** [comment]
Does `$THEOS` point to a symlink? That might be the underlying issue.
EDIT: Nevermind, if that were the case, it should have at least listed the path to `$THEOS` in the error.

**Comment by kabiroberai** [comment]
Are you sure you `export THEOS` in `~/.bash_profile`? Keeping it local won't work.

**Comment by mtshare** [comment]
After deleting `module/bin/update` and running the install script with `sudo` it works but I had to keep  `THEOS=/opt/theos` inside the install script even if have `export THEOS=/opt/theos` in my `~/.bash_profile`.

**Comment by kabiroberai** [comment]
Great! You may have forgotten to `sudo chown $(id -u):$(id -g) theos`. I'll add that point to **Installation** on the wiki.

**Comment by mtshare** [comment]
Thanks man and congratulation for the awesome work!

**Comment by Am1nCmd** [comment]
Hello I have the same question here
![image](https://user-images.githubusercontent.com/15339573/54881186-f33a2d00-4e7f-11e9-9cc2-461b5b802f93.png)

I'm trying to install theos but had that problem

I'm setting this in bash_profile
export THEOS=/Users/am1n47_/Documents/theos
export PATH=$THEOS/bin:$PATH

is there anything wrong?

**Comment by kabiroberai** [comment]
Could you please tell me the output of `echo $THEOS`?

**Comment by Am1nCmd** [comment]
There is no output


On Mar 30, 2019 at 10:22 PM, <Kabir Oberai<mailto:notifications@github.com>> wrote:


Could you please tell me the output of echo $THEOS?

**Comment by kabiroberai** [comment]
That means that the THEOS variable isn’t set. Ensure that your bash_profile file is located at `~/.bash_profile` – and if it still doesn’t work, try moving the export command to the top of the file
