### ISSUE TITLE
Failed to get codesign name

### ISSUE THREAD

**Issue by strano666** [kabiroberai/theos-jailed#21]
Hi.

I've successfully used the tool with many apps via the procedure described by `make info`.

I would automatize the entire process, so i've created the provisioning profile via [this tool](https://github.com/fastlane/fastlane/tree/master/sigh) . So i skip the phase with Xcode and the "fake" app. (it is right?)

The provisioning profile created, with the same id imposed in `make info`, is correctly installed under `/Users/<username>/Library/MobileDevice/Provisioning Profile`.

So i run `make package install PROFILE=<xxxx>.mobileprovision`, but i get this error
```
==> Error: Failed to get codesign name
make: *** [internal-package] Error 1
```

I've tried both the path under `/User/...` and the path inside the project when i've downloaded the provisioning profile.

**Comment by kabiroberai** [comment]
Try using the bundle ID instead of specifying the path to the .mobileprovision, making sure to delete any duplicate profiles first

**Comment by strano666** [comment]
If i use the bundle ID i've this error
```
==> Error: Could not find profile '<bundle ID>'
make: *** [internal-package] Error 1
```

I've already cleaned the dir of Provisioning Profile, indeed there is just one file.

**Comment by kabiroberai** [comment]
Sorry, ignore my last comment. The error you're getting means that it couldn't find the relevant certificate. Have you tried specifying `DEV_CERT_NAME`?

**Comment by kabiroberai** [comment]
Set it to `iPhone Developer: Whatever` (replace `Whatever` with your certificate name)

**Comment by strano666** [comment]
Just tried.
I've added at the top of Makefile
`DEV_CERT_NAME = iPhone Distribution: <name> (<ID>)`

Now i've a new error but during the installation
`==> Error: Error 0xe8008016: The entitlements specified in your application’s Code Signing Entitlements file do not match those specified in your provisioning profile. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)`

I've checked on the developer center the Provisioning Profile created, and the Certificate is for this Identity.

**Comment by kabiroberai** [comment]
Run `security cms -Di <file.mobileprovision>` and let me know the value of the `com.apple.developer.team-identifier` key. Does it match the ID in `DEV_CERT_NAME`?

**Comment by strano666** [comment]
Yep.

```
<key>com.apple.developer.team-identifier</key>
		<string><ID></string>
```

are the same.

**Comment by kabiroberai** [comment]
Does it work when you sign it with iOS App Signer?

**Comment by strano666** [comment]
You 're talking about [this project](https://dantheman827.github.io/ios-app-signer/)?

In this case, i've to try to sign the IPA generated under `packages` dir, and then install it?

**Comment by kabiroberai** [comment]
Yup

**Comment by strano666** [comment]
I've tried with iOS App Signer, using the mobileprovision by sigh/apple center and the profile put in the top of Makefile.

The signing process works, but if i try to install it via Xcode, i've the same error about entitlements.

If it can be useful, i've compared via `diff` the output of `security` command on the two different mobile provision file: that generated via Xcode, that's working, and that generated via sigh/apple center.

They are pretty similar, execept in obvious points (like time).
They have the same `<key>com.apple.developer.team-identifier</key>` but under the tag `<key>Name</key>` there is this situation:

Apple Center:
```
<key>Name</key>
<string>_<right bundle id>_ AppStore</string>
```

Xcode:
```
<key>Name</key>
<string>iOS Team Provisioning Profile: _<right bundle id>_ </string>
<key>ProvisionedDevices</key>
<array>
<string><device id></string>
</array>
```

So in the provisioning profile by Apple Center, the tag ProvisionedDevices is missing.

**Comment by strano666** [comment]
The problem was there!

The provisioning profile was for the App Store, so without `ProvisionedDevice`. I've changed the kind of the develop and everything works!

**Comment by hoangpx** [comment]
how did you fix this ? Could you explain for me how to fix this ?
