### ISSUE TITLE
Error: Codesign failed make: *** [internal-package] Error 1

### ISSUE THREAD

**Issue by kaaslikker2** [kabiroberai/theos-jailed#25]

**Comment by kaaslikker2** [comment]
getting this error after signing

**Comment by kabiroberai** [comment]
Please thoroughly read [General Usage](https://github.com/kabiroberai/theos-jailed/wiki/Usage#general-usage) and [Troubleshooting](https://github.com/kabiroberai/theos-jailed/wiki/Troubleshooting) before creating an issue, as they cover this topic.

**Comment by kabiroberai** [comment]
If the issue still persists, let me know and I'll reopen this (but please attach the `troubleshoot` output)
