### ISSUE TITLE
Bypass Hash Check?

### ISSUE THREAD

**Issue by Cryptiiiic** [kabiroberai/theos-jailed#26]
So Injustice 2 has this annoying hash check which uses a crc file and if it doesn't match, you can't connect/play online. Is there anyway around this. When I use theos jailed with the app. I can't connect online. I think you are gonna tell me to figure it out myself.

**Comment by kabiroberai** [comment]
I'm not sure about the exact implementation of the check, but I recommend disassembling the game in Hopper and seeing whether there's a method that does the check. If there is, use Fishhook to interpose it and make it indicate success

**Comment by Cryptiiiic** [comment]
@kabiroberai I have done that but only found:

dd "CRC Error" and when I NOP the xref it still won't let me connect online.

**Comment by kabiroberai** [comment]
NOPing the xref to the string won't be enough. You'll need to NOP the logic instead (or modify the control flow).

**Comment by Cryptiiiic** [comment]
@kabiroberai I phrased it wrong. I double clicked on the xref and nop the region that that address is in.

**Comment by kabiroberai** [comment]
This seems like more of an app-specific issue than one with Theos Jailed in general, and also you'd probably be better off using Hopper to tweak games. I'm closing this issue because I’m not sure how I can help, but I’d recommend asking on /r/jailbreakdevelopers, IRC, or the jailbreak discord.
