### ISSUE TITLE
importing dylib within tweak.xm

### ISSUE THREAD

**Issue by ninoz** [kabiroberai/theos-jailed#30]
Hi

Im trying to import the following DYLIB:
https://github.com/iSECPartners/ios-ssl-kill-switch ( I downloaded the .deb and unpacked the dylib)
Within the following IPA file:
http://damnvulnerableiosapp.com/

My make file looks like:
```
MODULES = jailed
include $(THEOS)/makefiles/common.mk

TWEAK_NAME = DVIAJAILED
DISPLAY_NAME = DVIAJAILED
BUNDLE_ID = com.highaltitudehacks.dvia
DVIAJAILED_USE_FLEX = 1
DVIAJAILED_FILES = Tweak.xm
DVIAJAILED_IPA = /Users/nino/Downloads/DVIA.ipa
DVIAJAILED_EMBED_LIBARIES = $(THEOS_MAKE_PATH)/SSLKillSwitch.dylib

include $(THEOS_MAKE_PATH)/tweak.mk

```

However im a bit confused on Step 5:
`#import <foo.h>`

How can I tell what the correct header is?

**Comment by ninoz** [comment]
I was being an idiot, I should have used TWEAK_NAME_INJECT_DYLIBS!

**Comment by kabiroberai** [comment]
Not strictly related to the issue, but did the dylib work? Afaik it uses MSHookFunction, which doesn’t work correctly in sandboxed environments

**Comment by ninoz** [comment]
So it does load and I get messages in the log, I had to edit the source as the preference plist wasnt present.

Whilst it loads, I found that on my jailed phone DVIA still pinned the certificate.  If I installed the same IPA on my jailbroken phone it bypassed the certificate so I think the sandboxed environment is stopping it.
I did start a conversation with the developer, I'm going to look more into it over the weekend
 
https://github.com/nabla-c0d3/ssl-kill-switch2/issues/31

**Comment by kabiroberai** [comment]
Hmm, apparently you can set a flag to use fishhook instead (the same thing used by Theos Jailed for C function interposing), so there's a chance that you can get it to work. Let me know if you figure it out, because I may make it an addon. Good luck!
