### ISSUE TITLE
Is ARC enabled?

### ISSUE THREAD

**Issue by strano666** [kabiroberai/theos-jailed#32]
Is ARC for automatic reference counting enabled?

**Comment by kabiroberai** [comment]
ARC isn't enabled by default, but if you need it then you can add `<Tweak Name>_CFLAGS = -fobjc-arc` to your makefile. See [this](http://iphonedevwiki.net/index.php/Using_ARC_in_tweaks) article for more info.

**Comment by strano666** [comment]
Hi @kabiroberai , 
i've checked, before this answer, via `otool -I -v Payload/<APP_NAME>.app/APP_NAME` about ARC.

Without modify the Makefile, results enabled.
Just for info.

Thank you anyway!

**Comment by kabiroberai** [comment]
I think you’re confused between the app executable and the tweak dylib. Although the main app may have ARC, your tweak won’t unless you explicitly enable it. But if you just wanted to check whether the main app has it or not, then what you did should be fine.

Either way, welcome 🙂
