### ISSUE TITLE
Failed to nicify template

### ISSUE THREAD

**Issue by itsMaz1n** [kabiroberai/theos-jailed#35]
When make template "jailed.nic.tar"
```
Successfully installed module.
Error: Failed to nicify template
```
**Note**: all files: Makefile NIC theos Tweak.xm in
~/templates/ios/kabiroberai

**Comment by kabiroberai** [comment]
Could you please run `pwd && ls template/` and let me know the output? Make sure to `cd` into the Theos Jailed directory first

**Comment by itsMaz1n** [comment]
`/opt/theos
ios
`
