### ISSUE TITLE
Modify IPA Name without being removed

### ISSUE THREAD

**Issue by Amuyea** [kabiroberai/theos-jailed#39]
Hello, I thought of this idea but I'm not sure if it's possible.

After compiling the Jailed Project, new ipa will be in the package folder of Jailed Project. 
If I changed name or added another IPA to the folder & compiled the project again. All of the files in the package folder will be deleted and only ipa from project will be there. Is there a way to stop this from happening?

**Comment by kabiroberai** [comment]
Theos Jailed currently deletes all old ipa files in the packages dir, as they tend to take up a lot of space on disk. If you want to disable this, you can either move the ipa out of packages, change the .ipa extension to something else (eg .ipa.old), or comment out [this line](https://github.com/kabiroberai/theos-jailed/blob/master/module/bin/ipa.sh#L117) and run the install script again.

**Comment by Amuyea** [comment]
I tried to comment that line out and it still remove the *.ipa from the directory.

**Comment by kabiroberai** [comment]
Did you run `./install` again?

**Comment by Amuyea** [comment]
Tried it few times and it works. Thanks!

**Comment by kabiroberai** [comment]
Welcome 🙂
