### ISSUE TITLE
UIDebuggingInformationOverlay on iOS 11

### ISSUE THREAD

**Issue by nullpixel** [kabiroberai/theos-jailed#40]
In another issue, you said you thought this was removed. However, after checking headers, it is indeed present - I can look into why this doesn't present.

**Comment by kabiroberai** [comment]
I've reopened #23 with an update on the situation regarding `UIDebuggingInformationOverlay`, so I'm closing this issue in favour of that one. If you have any additional findings, feel free to add them to that issue.
