### ISSUE TITLE
theos-jailed working on windows?

### ISSUE THREAD

**Issue by Antonn1** [kabiroberai/theos-jailed#42]
With the new https://msdn.microsoft.com/en-au/commandline/wsl/install_guide released, is it possible to get this working on windows/linux now? for those that don't have a mac? :D

At least the packaging stage as for sideloading user can use cydia impactor @kabiroberai

**Comment by kabiroberai** [comment]
Hey, once Theos Jailed gets support for building tweaks on jailbroken iOS devices (GNU), it should more or less support WSL as well. I'll merge this into #9 and try to get it working as soon as possible.
