### ISSUE TITLE
output_name not changing anything

### ISSUE THREAD

**Issue by Antonn1** [kabiroberai/theos-jailed#43]
hey!

i'm trying to set a custom package output name on my Makefile but nothing happens?

i noticed output_name in common.mk and set it in makefile:

OUTPUT_NAME = Test.ipa

but nothing happens? something i'm doing wrong or is it not possible? 

Thank you!!!

**Comment by kabiroberai** [comment]
Try `override OUTPUT_NAME = Test.ipa`

**Comment by Antonn1** [comment]
Worked! Thanks!
