### ISSUE TITLE
Question: Does theos-jailed support iOS 7?

### ISSUE THREAD

**Issue by iOSGods** [kabiroberai/theos-jailed#45]
Hello,

Currently have no iOS 7 device to test this but considering it says from iOS 8 up to iOS 11 is supported, I'm guessing iOS 7 is not? Is there a reason for this? Just wondering. :)

Thank you for your time!

**Comment by kabiroberai** [comment]
iOS only got official support for embedded dylibs in iOS 8, so I assumed that iOS 7 wouldn't be supported.

I don't have an iOS 7 device to confirm this either, but if you manage to get a Theos Jailed tweak running on iOS 7, let me know and I'll update the repo's description 🙂

**Comment by iOSGods** [comment]
I know a user who has an iPhone 5s with iOS 7 and I'm assuming it works for him since he hasn't said that it doesn't. But I will find an iPhone 4 very soon and get back to this with an answer. :)

**Comment by iOSGods** [comment]
I tried it with one app and it just got stuck on "verifying application" :/

**Comment by kabiroberai** [comment]
That might be an issue with ios-deploy. Does it work if you use Impactor?

**Comment by iOSGods** [comment]
Actually, that was on Impactor. I never used ios-deploy. :p

**Comment by kabiroberai** [comment]
Closing because from the above conversation it appears that Theos Jailed doesn’t work on iOS 7. If you have any new info feel free to leave a comment.

**Comment by ghost** [comment]
I need help regarding this how to use it any video
