### ISSUE TITLE
Failed to nicify template

### ISSUE THREAD

**Issue by tin4g** [kabiroberai/theos-jailed#49]
**INFORMATIONS**

- [theos](https://github.com/theos/theos) worked and using [theos-jailed](https://github.com/kabiroberai/theos-jailed/commit/3cb40dc32a5d63aadf6eda0416aa8f7a30fb26b4) 

- `pwd && ls -a template/`

```
~/.local/opt/theos-jailed
.        ..       Makefile NIC      Tweak.xm theos
```

- `$THEOS/bin/nicify.pl template/`

```
dyld: lazy symbol binding failed: Symbol not found: _Perl_xs_handshake
  Referenced from: ~/.perl5/lib/perl5/darwin-thread-multi-2level/auto/Compress/Raw/Zlib/Zlib.bundle
  Expected in: flat namespace

dyld: Symbol not found: _Perl_xs_handshake
  Referenced from: ~/.perl5/lib/perl5/darwin-thread-multi-2level/auto/Compress/Raw/Zlib/Zlib.bundle
  Expected in: flat namespace

Abort trap: 6
```

**SOLUTIONS**

- **[Temporary]** Providing the tar file

**Comment by kabiroberai** [comment]
Could you try nicify-ing another template from https://github.com/theos/templates?

**Comment by tin4g** [comment]
The same problem occurred. Perhaps my Homebrew is incorrect. Could you provide one tar file?

**Comment by kabiroberai** [comment]
If the same issue occurs when nicifying other templates, it's an issue with Theos, not Theos Jailed. For now download https://transfer.sh/Zjk6N/iphone_jailed.nic.tar and place it in the same directory as `install`. Then delete line 41 of `install` and run it.

**Comment by kabiroberai** [comment]
To get help regarding nicify.pl, you should create a new issue in https://github.com/theos/nic.
