### ISSUE TITLE
Not everything signed?

### ISSUE THREAD

**Issue by meinname** [kabiroberai/theos-jailed#5]
Hi,

with Deezer Music (https://itunes.apple.com/app/deezer-music/id292738169?mt=8) i noticed following:
When i build a iPA and install it via make install via xcode/itunes the app crashes on iOS 10 when a song is playing, the device is locked and the devices gets woken up but not unlocked (e.g. via powerbutton). 
But if i take exactly then same iPA (from packages dir) and push it via cydia impactor to my device it won't crash. 
So maybe not everything needed to be signed is signed by ipa.sh? 

Sorry I can't compare the files pushed by cydia impactor to the device with the content of the ipa cause i have atm no jailbroken device.

//edit: Crash also happens when signing with iOS App Signer also with some resigning services i tested. Only cydia impactor seems to do it right. (but as i don't have a dev account i only get a 7 day cert with it)

**Comment by kabiroberai** [comment]
Did you create a profile by following the instructions in `make info`? It may require the `Inter-App Audio` capability to be enabled.

**Comment by meinname** [comment]
make info only wants
>>> Wireless Accessory Configuration
>>> App Groups

But shouldn't matter as i use a Wildcard Profile

**Comment by kabiroberai** [comment]
Upon inspecting the binary's entitlements, it seems that it has an unknown key, `com.apple.developer.playable-content`. This might be what's causing the crash.

**Comment by kabiroberai** [comment]
I think it might be to do with CarPlay, so it's probably not the issue in that case

**Comment by meinname** [comment]
So you have  tried it too and you can confirm my observation?

I still think Cydia Impactor signs at least one file more.

**Comment by kabiroberai** [comment]
I haven't been able to test it out yet, but try using a custom profile anyways and see if that works.

**Comment by meinname** [comment]
Sorry, i'm no Developer. 
I only bought a cert + a wildcard profile for my device for a few bucks ;)

**Comment by kabiroberai** [comment]
I meant to say a profile using a regular Apple ID (just follow `make info`)

**Comment by meinname** [comment]
Ok, that's interesting.
Did what you said and it doesn't crash.

//edit: more interesting: even without adding Wireless Accessory Configuration and App Groups it doesn't crash

**Comment by kabiroberai** [comment]
Are you sure you reinstalled the profile after disabling them?

**Comment by meinname** [comment]
I set a new identifier, deleted the profile from Device, did the build for the app in xcode again, had to trust the dev this time, deleted to app and used the new id on PROFILE=

Maybe it's because of the Apple Watch? The Wildcard Profile doesnt't include the Watch. The one generated by XCode does.

**Comment by kabiroberai** [comment]
Well, I don't think it matters much anyways since it worked, so I'm closing this issue for now. There isn't anything I can do to change the fact that it doesn't work with wildcard profiles (it might be an in-app check), although feel free to look into it yourself.

**Comment by kabiroberai** [comment]
If you want, you can upload your crash log here (`window > devices > view device logs` in Xcode), and that might give us a hint as to what the problem was.

**Comment by meinname** [comment]
Here are the Logs. Removed the Devicelogs before and let it crash/hang 2 times.  


[crashlogs.zip](https://github.com/kabiroberai/theos-jailed/files/677478/crashlogs.zip)

**Comment by kabiroberai** [comment]
As speculated, this crash is probably due to the application itself and not the profile (might be the application checking the profile though). See [this StackOverflow answer](http://stackoverflow.com/a/18997360) related to the error code in your crash
