### ISSUE TITLE
Import a 3rd party library inside Theos Jailed project

### ISSUE THREAD

**Issue by istornz** [kabiroberai/theos-jailed#51]
Hello all,

First, thanks for the amazing project !
I want to import a private 3rd party library called [**SocketRocket**](https://github.com/facebook/SocketRocket) inside a jailed Theos project.
I tried to copy the **SocketRocket.framework** file inside _/opt/theos/include/PrivateFrameworks/_ and adding 

`ADDITIONAL_CFLAGS += -I$(THEOS)/include/PrivateFrameworks`

inside the Makefile but when I try to compile I have 

```
Tweak.xm:3:9: fatal error: 'SocketRocket/SocketRocket.h' file not found
#import <SocketRocket/SocketRocket.h>
```

Best regards,
Dimitri

**Comment by kabiroberai** [comment]
Hey! Firstly apologies for the late response – I forgot to reply when you opened the issue. For future reference, be sure to check out the [Usage](https://github.com/kabiroberai/theos-jailed/wiki/usage) page on the wiki for more info on importing frameworks.
