### ISSUE TITLE
is there a way to hide my code from dylib 

### ISSUE THREAD

**Issue by hadoiz** [kabiroberai/theos-jailed#54]
i want to hide my admob ad banner id in my tweak is there any option so no one can change my unit id ad?!

**Comment by kabiroberai** [comment]
This question is not directly related to Theos Jailed, but rather applies to tweak development in general. I would recommend asking this question in the #developers channel of the [r/jailbreak Discord](http://discord.gg/jb) or at [r/jailbreakdevelopers](https://www.reddit.com/r/jailbreakdevelopers).
