### ISSUE TITLE
how to creat info.plist for my tweak 

### ISSUE THREAD

**Issue by hadoiz** [kabiroberai/theos-jailed#56]
can i creat info.plist to makefile ? and what about libray.a files i can inculde it to and how thanx ??
i want to creat info.plist to add  NSAllowsArbitraryLoads  and about libray,a i need to creat appnext ads so its need library,a files

**Comment by kabiroberai** [comment]
Please see https://github.com/kabiroberai/theos-jailed/wiki/Usage#adding-resources – you can create an Info.plist file in your project's Resources directory with the required key, which will be merged with the app's Info.plist during packaging.
