### ISSUE TITLE
Help me install?

### ISSUE THREAD

**Issue by kuteteen** [kabiroberai/theos-jailed#6]
I'm use mac el captain and xcode 7.3!  But install theos of you error. Help me guide install.please!!!

**Comment by kuteteen** [comment]
Help me please

**Comment by kabiroberai** [comment]
What error are you getting?

**Comment by kuteteen** [comment]
i update code : sudo ./update
but error:
Error: "" is not a directory. Aborting...
help me please fix. on mac os

**Comment by kuteteen** [comment]
make packages
2016-12-29 13:06:04.810 xcodebuild[853:15537] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SamplePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs

**Comment by kabiroberai** [comment]
The `$THEOS` variable doesn't seem to be set correctly, make sure you followed Theos' [installation](https://github.com/theos/theos/wiki/Installation) instructions before using Theos Jailed.

**Comment by kuteteen** [comment]
ld: warning: invalid -install_name (@executable_path/CydiaSubstrate) in dependent dylib (/Users/osxvn/sc/theos/lib/libsubstrate.dylib). Dylibs/frameworks which might go in dyld shared cache cannot link with dylib that uses @rpath, @loader_path, etc.

please fix :(

**Comment by kuteteen** [comment]
and errorld: warning: object file (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/lib/darwin/libclang_rt.ios.a(emutls.c.o)) was built for newer iOS version (6.0) than being linked (3.0)

help me fix :(

**Comment by kabiroberai** [comment]
Are you sure you aren't using the legacy version of Theos? [Upgrade](https://github.com/theos/theos/wiki/Upgrading-from-legacy-Theos) Theos to the latest version before using this module.

**Comment by kuteteen** [comment]
i'm using BishopFox and update module of you.but error make. help me !please give me a basic guide ..I'm not good at English. sorry!

**Comment by kabiroberai** [comment]
This repository is a replacement for BishopFox's theos-jailed, so you have
to install it with the regular Theos. You have to delete the BishopFox one
before installing this.

**Comment by kabiroberai** [comment]
Once you've deleted BishopFox's Theos Jailed, install the latest Theos and this module by following [these instructions](https://github.com/kabiroberai/theos-jailed/wiki/Installation)

**Comment by kuteteen** [comment]
Help me make video guide install on mac os!! Please..i'm so so thanks you

**Comment by kuteteen** [comment]
please :(

**Comment by kabiroberai** [comment]
I don't have the time to make a video tutorial, but I might make a written guide soon

**Comment by kuteteen** [comment]
help me add uialertview code example in tweak.xm. i add but not working !

**Comment by kabiroberai** [comment]
Can you please attach your Tweak.xm and Makefile here?

**Comment by kuteteen** [comment]
a cd directory of `theos` and `make update-jailed`. but error :( 
`make: *** No rule to make target `update-jailed.  Stop.`

P/S:and . i using `./update `working :D

**Comment by kabiroberai** [comment]
You need to `cd` into a project directory to run `make update-jailed`.
Since your initial problem has been resolved, I'm closing this issue. If you have any further problems, create a new issue after reading https://github.com/kabiroberai/theos-jailed/wiki/Troubleshooting.
