### ISSUE TITLE
Update FLEX addon to 4.1.1

### ISSUE THREAD

**Issue by miuirussia** [kabiroberai/theos-jailed#63]
https://github.com/Flipboard/FLEX/tree/4.1.1

**Comment by kabiroberai** [comment]
Hey, thanks for the reminder; I'll try to update FLEX as soon as I can. This will also probably require adjustments to the addon's `Makefile`, as it appears that there aren't just .m and .h files anymore

**Comment by kabiroberai** [comment]
Done in 5de4d70. Could you please check whether that commit works? I'll close this issue after that.

**Comment by kabiroberai** [comment]
I've tested this and it appears to work fine. Closing once #68 is merged.
