### ISSUE TITLE
Injecting dylib and its files

### ISSUE THREAD

**Issue by LaxusiC** [kabiroberai/theos-jailed#65]
I have a tweakname.dylib and its folder called tweakname.bundle (I get in /Library/Application Support/) Is it possible to inject the tweakname.bundle?

**Comment by syto203** [comment]
You can add the bundle by creating a folder and name it “Resources” inside your tweak working directory and place the .bundle inside it.

And follow the rest of the instructions from the wiki
https://github.com/kabiroberai/theos-jailed/wiki/Usage#adding-resources
