### ISSUE TITLE
Error when I try to "make package"

### ISSUE THREAD

**Issue by Eduar21** [kabiroberai/theos-jailed#66]
Making stage for tweak pandoads…
cp: /Users/pcname/Desktop/Tweaks/testads/.theos/_/Applications: No such file or directory

==> Error: Can't access app path '/Users/pcname/Desktop/Tweaks/testads/.theos/_/Payload/*.app' : No such file or directory

**Comment by syto203** [comment]
make sure the IPA is correctly packed. if you converted a deb to ipa or extracted one from xcode make sure the root of the ipa contains the "Payload" folder and inside that the ".app". if the folder is named "Applications" rename it to "Payload".

|__your-ipa.ipa
| |____Payload
| | |____anyApp.app

**Comment by Eduar21** [comment]
I just fix the problem thanks, the folder where I have my IPAS have a space I delete the space and now works thanks for give a idea where to look.

**Comment by Eduar21** [comment]
> make sure the IPA is correctly packed. if you converted a deb to ipa or extracted one from xcode make sure the root of the ipa contains the "Payload" folder and inside that the ".app". if the folder is named "Applications" rename it to "Payload".
> 
> |__your-ipa.ipa
> | |____Payload
> | | |____anyApp.app

Is a app from AppStore I use cynject to get the ipa decrypted I try with lower version of the app too but I'm still getting the same problem.

**Comment by kabiroberai** [comment]
What are the contents of your `Makefile`? Additionally, please run `make clean package messages=yes` and provide the output here.

**Comment by Eduar21** [comment]
> What are the contents of your `Makefile`? Additionally, please run `make clean package messages=yes` and provide the output here.

Here is my output of ''make clean package message=yes'' 
https://pastebin.com/VwZAKvDc

and this is my Makefile
https://pastebin.com/7YSgQBZ7

**Comment by Eduar21** [comment]
> What are the contents of your `Makefile`? Additionally, please run `make clean package messages=yes` and provide the output here.

Here this is my Output of make clean package message=yes
https://pastebin.com/VwZAKvDc

my Makefile 
http://pastebin.com/TXbE8WmQ

**Comment by ifonefreak** [comment]
I have a similar issue..please help if you can guys ! thanks

I'm getting:
> Making stage for tweak test…
cp: /Users/Maniac/test/.theos/_/Applications: No such file or directory

**Comment by kabiroberai** [comment]
This should be resolved by ee0e15b. Could you please [update Theos Jailed](https://github.com/kabiroberai/theos-jailed/wiki/Installation#updating) and check whether the issue persists?

**Comment by ifonefreak** [comment]
Now it works ! thank you so much!

**Comment by kabiroberai** [comment]
Awesome, no problem :)
