### ISSUE TITLE
Error: Could not find profile '*'

### ISSUE THREAD

**Issue by Antonn1** [kabiroberai/theos-jailed#7]
Hi!

Im new to theos on Mac and i was able to set everything up properly but upon making i always get that error Error: Could not find profile '*'

im not sure if that error is because of my Mac or because of theos-jailed and would appreciate any help!

**Comment by kabiroberai** [comment]
Hey, what command are you running? If you don't have a paid developer account, you have to run `make package install PROFILE=<your profile>` (note the `PROFILE=` part). To learn how to set up a profile, run `make info`.

**Comment by kabiroberai** [comment]
If you don't want to always set `PROFILE=<your profile>`, just that line to the top of `Makefile`.

**Comment by Antonn1** [comment]
Thank you! that helped me.

is it possible to make theos jailed just create the modified ipa without having to sign then install it? is there an option just for that? make package also signs it unfortunately,

**Comment by kabiroberai** [comment]
As a matter of fact, there is! Just set `CODESIGN_IPA=0` in Makefile or when running `make package`.

**Comment by Antonn1** [comment]
thank you brother you are awesome!
