### ISSUE TITLE
libbulletin notification bt sport app

### ISSUE THREAD

**Issue by gb160** [kabiroberai/theos-jailed#72]
Just a quick question:

Is it possible to send notifications with libbulletin?

**Comment by kabiroberai** [comment]
libbulletin seems to hook into SpringBoard so I don't think so. Have you considered using the [UserNotifications](https://developer.apple.com/documentation/usernotifications) framework?

**Comment by gb160** [comment]
That was my suspicion, thanks for confirming.

I haven't looked in UserNotifications framework, however I will now! Thanks for the suggestion mate.

**Comment by gb160** [comment]
I don't suppose you know of an example anywhere showing this in action?
