### ISSUE TITLE
current status of this projects maintainment

### ISSUE THREAD

**Issue by Directory** [kabiroberai/theos-jailed#76]
the last commit was 2 years ago with most being 4-6 years old. I have not used this yet so I do not know if I will run into issues but my only question is, is this project abandoned? or has their been no major breaking changes with Theos or the iOS ecosystem and therefore no updates are needed yet?

**Comment by kabiroberai** [comment]
I've been busy with college lately but afaik Theos Jailed works fine on iOS 15 and with the latest Theos commits. If you face any problems don't hesitate to create a new issue, and if you have general questions feel free to reach out to me on the [Theos discord server](https://theos.dev/discord).
