### ISSUE TITLE
Asking for Password.

### ISSUE THREAD

**Issue by Amuyea** [kabiroberai/theos-jailed#8]
I understand how to make deb so but I don't understand why it's asking for password. 

```
AGs-MacBook-Pro:ufctv Amuyea$ make package install
> Making all for tweak ufctv…
make[2]: Nothing to be done for `internal-library-compile'.
> Making stage for tweak ufctv…
dpkg-deb: warning: deprecated compression type 'lzma'; use xz instead
dpkg-deb: warning: ignoring 1 warning about the control file(s)
dpkg-deb: building package 'com.amuyea.ufctv' in './packages/com.amuyea.ufctv_0.0.1-21+debug_iphoneos-arm.deb'.
==> Installing…
Password:
Password:
Password:
Permission denied (publickey,keyboard-interactive).
make: *** [internal-install] Error 255
```

```
AGs-MacBook-Pro:ufctv Amuyea$ make install
==> Installing…
Password:
Password:
Password:
Permission denied (publickey,keyboard-interactive).
make: *** [internal-install] Error 255
```

Could you be clear of what I should do. Thanks

**Comment by kabiroberai** [comment]
It seems that you accidentally selected the `tweak` template instead of `jailed`. Please recreate the project with the correct template, and try again (it's option 7 by default).

**Comment by Amuyea** [comment]
Opps. Thanks for help. 

I have a question. Does it allows us to use writeData method or MShook?

**Comment by kabiroberai** [comment]
Since Theos Jailed uses Substrate, MSHook should work. I'm not sure about write data, but that should work too in the documents directory.
